export const SUPPLIER_ADD_REQUEST = "SUPPLIER_ADD_REQUEST";
export const SUPPLIER_ADD_SUCCESS = "SUPPLIER_ADD_SUCCESS";
export const SUPPLIER_ADD_FAIL = "SUPPLIER_ADD_FAIL";
export const SUPPLIER_ADD_RESET = "SUPPLIER_ADD_RESET";

export const SUPPLIER_GET_REQUEST = "SUPPLIER_GET_REQUEST";
export const SUPPLIER_GET_SUCCESS = "SUPPLIER_GET_SUCCESS";
export const SUPPLIER_GET_FAIL = "SUPPLIER_GET_FAIL";
export const SUPPLIER_GET_RESET = "SUPPLIER_GET_RESET";

// export const CLIENTS_UPDATE_REQUEST = "CLIENTS_UPDATE_REQUEST";
// export const CLIENTS_UPDATE_SUCCESS = "CLIENTS_UPDATE_SUCCESS";
// export const CLIENTS_UPDATE_FAIL = "CLIENTS_UPDATE_FAIL";
// export const CLIENTS_UPDATE_RESET = "CLIENTS_UPDATE_RESET";

// export const CLIENTS_TOGGLE_REQUEST = "CLIENTS_TOGGLE_REQUEST";
// export const CLIENTS_TOGGLE_SUCCESS = "CLIENTS_TOGGLE_SUCCESS";
// export const CLIENTS_TOGGLE_FAIL = "CLIENTS_TOGGLE_FAIL";

// export const CLIENTS_SEARCH_REQUEST = "CLIENTS_SEARCH_REQUEST";
// export const CLIENTS_SEARCH_SUCCESS = "CLIENTS_SEARCH_SUCCESS";
// export const CLIENTS_SEARCH_FAIL = "CLIENTS_SEARCH_FAIL";
